### ISSUE TITLE
rss-feed-reader page blocked by AdGuard

### ISSUE THREAD

**Issue by jeremygaither** [ucg8j/blog#6]
The page <https://lukesingham.com/rss-feed-reader/> and the source <https://github.com/ucg8j/blog/blob/master/posts/rss-feed-reader.md> are getting blocked by AdGuard for some reason. I don't believe there is malicious content on the page. Here's the AdGuard issue: https://github.com/AdguardTeam/AdguardFilters/issues/82423

**Comment by ucg8j** [comment]
Apologies for not getting to this earlier. 

Thanks for raising the issue here and on AdGuard. I couldn't replicate the issue unfortunately, and I use the same lists with the UblockOrigin Firefox addon. I tried to [verify this diagnosis](https://github.com/AdguardTeam/AdguardFilters/issues/82423#issuecomment-839035376) by [this search](https://github.com/easylist/easylist/search?q=rss-feed-reader.md) and [this search](https://github.com/easylist/easylist/search?q=lukesingham) on the lists repo - but couldn't find anything.

Hope you managed to get around the issue.
